
#ifndef SEARCHER_H
#define SEARCHER_H


#include "Tokenizer.h"
#include "TernarySearchTree.h"
#include "Indexer.h"
#include "WordLocation.h"

#include <iostream>
#include <fstream>
#include <cmath>
#include <algorithm>
#include <vector>
#include <unordered_map>
#include <map>


/**
 * Handles all search operations over built index :
 * - Exact term search
 * - Prefix search via TST
 * - Multi-word and mixed (multi + prefix) queries
 * - TF-IDF ranking
 *
 * The Searcher uses the index generated by Indexer and a 
 * Ternary Search Tree for prefix expansions. Results are 
 * ranked by TF-IDF relevance scores and previous token position.
 */
class Searcher {
private:
    const std::unordered_map<std::string, std::unordered_map<std::string, std::vector<WordLocation>>>& index;
    const TernarySearchTree& tst;
    Tokenizer tokenizer;

    std::vector<WordLocation> positionalIntersect(const std::vector<WordLocation>& pos1, const std::vector<WordLocation>& pos2);

    std::unordered_map<std::string, std::unordered_map<std::string, std::vector<WordLocation>>> chainedPositionalIntersect(
    const std::unordered_map<std::string, std::unordered_map<std::string, std::vector<WordLocation>>>& index,
    const std::vector<std::string>& queryTokens);





    // will return a unsorted vector of this prefix partial token.
    std::vector<std::string> expandToken(const std::string& token) const;

    double computeTF(size_t termCountInDoc, size_t totalTermsInDoc) const;

    double computeIDF(size_t docsContainingTerm, size_t totalDocs) const;
    // added previousToken
    std::vector<std::pair<std::string, double>> computeScores(const std::unordered_map<std::string, std::unordered_map<std::string, std::vector<WordLocation>>>& results) const;
public:
    // default constructor
    Searcher(const std::unordered_map<std::string, std::unordered_map<std::string, std::vector<WordLocation>>>& idx,
             const TernarySearchTree& tst);
             
    std::unordered_map<std::string, std::unordered_map<std::string, std::vector<WordLocation>>> search(const std::string& query);
};

#endif
